# MCP Servers Configuration
# This file defines the MCP server endpoints and configurations for UFO2

# MCP Server Configuration
mcp_servers:
  powerpoint:
    name: "PowerPoint MCP Server"
    description: "MCP server for Microsoft PowerPoint automation and control"
    endpoint: "http://localhost:8001"
    instructions_path: "config/mcp_instructions/powerpoint.yaml"
    timeout: 30
    retry_count: 3
    health_check_endpoint: "/health"
    tools_endpoint: "/tools"
    execute_endpoint: "/execute_tool"
    enabled: true
    
  word:
    name: "Word MCP Server"
    description: "MCP server for Microsoft Word automation and document manipulation"
    endpoint: "http://localhost:8002"
    instructions_path: "config/mcp_instructions/word.yaml"
    timeout: 30
    retry_count: 3
    health_check_endpoint: "/health"
    tools_endpoint: "/tools"
    execute_endpoint: "/execute_tool"
    enabled: true
    
  excel:
    name: "Excel MCP Server"
    description: "MCP server for Microsoft Excel automation and spreadsheet manipulation"
    endpoint: "http://localhost:8003"
    instructions_path: "config/mcp_instructions/excel.yaml"
    timeout: 30
    retry_count: 3
    health_check_endpoint: "/health"
    tools_endpoint: "/tools"
    execute_endpoint: "/execute_tool"
    enabled: true
    
  web:
    name: "Web MCP Server"
    description: "MCP server for web browser automation and web page interaction"
    endpoint: "http://localhost:8004"
    instructions_path: "config/mcp_instructions/web.yaml"
    timeout: 30
    retry_count: 3
    health_check_endpoint: "/health"
    tools_endpoint: "/tools"
    execute_endpoint: "/execute_tool"
    enabled: true
    
  shell:
    name: "Shell MCP Server"
    description: "MCP server for shell command execution and system operations"
    endpoint: "http://localhost:8005"
    instructions_path: "config/mcp_instructions/shell.yaml"
    timeout: 30
    retry_count: 3
    health_check_endpoint: "/health"
    tools_endpoint: "/tools"
    execute_endpoint: "/execute_tool"
    enabled: true

# Global MCP Configuration
global_config:
  # Connection settings
  connection_timeout: 10
  read_timeout: 30
  max_retries: 3
  retry_delay: 1.0
  
  # Logging settings
  log_requests: true
  log_responses: true
  log_level: "INFO"
  
  # Error handling
  fallback_to_ui: true
  ignore_connection_errors: false
  
  # Performance settings
  connection_pool_size: 10
  keep_alive: true
  
  # Security settings
  verify_ssl: true
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
  
# Application mapping - maps app names to MCP servers
app_mapping:
  "POWERPNT.EXE": "powerpoint"
  "WINWORD.EXE": "word"
  "EXCEL.EXE": "excel"
  "powerpoint": "powerpoint"
  "word": "word"
  "excel": "excel"
  "msedge.exe": "web"
  "chrome.exe": "web"
  "firefox.exe": "web"
  "cmd.exe": "shell"
  "powershell.exe": "shell"
  "pwsh.exe": "shell"

# Tool categories and preferences
tool_preferences:
  # Prefer MCP tools for these operations
  preferred_operations:
    - "document_creation"
    - "presentation_creation"
    - "spreadsheet_manipulation"
    - "web_automation"
    - "file_operations"
    - "data_export"
    - "template_usage"
  
  # Fallback to UI for these operations
  ui_fallback_operations:
    - "complex_ui_interactions"
    - "visual_verification"
    - "screenshot_capture"
    - "unknown_operations"

# Health monitoring
health_monitoring:
  enabled: true
  check_interval: 60  # seconds
  failure_threshold: 3
  recovery_threshold: 2
  alert_on_failure: true

# Development and debugging
development:
  mock_servers: false
  local_testing: true
  debug_mode: false
  trace_requests: false
